/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package java_contact_app;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import java.net.URL;

/**
 *
 * @author Sir
 */
public class MyContact_Form extends javax.swing.JFrame {

    /**
     * Creates new form MyContact_Form
     */
    
    String imagePth = null;
    public static int currentUserId;
    int pos = 0;
    
    public MyContact_Form() throws SQLException {
        initComponents();
        populateJtable();
        
        jTable1.setShowGrid(true);
        jTable1.setGridColor(Color.yellow);
        jTable1.setSelectionBackground(Color.lightGray);
        
        JTableHeader th = jTable1.getTableHeader();
        th.setForeground(Color.blue);
        th.setFont(new Font("Tahoma", Font.PLAIN, 11));
        System.out.println(currentUserId+"Form Contact");
        
        ImageIcon myImg = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("1.jpg")));
        Image img = myImg.getImage().getScaledInstance(jLabel_imageicon.getWidth(), jLabel_imageicon.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon myPic = new ImageIcon(img);
        jLabel_imageicon.setIcon(myPic);
        
//        Image pic = ((ImageIcon) jTable1.getValueAt(rowIndex, 6)).getImage().getScaledInstance(jLabelContact_picture.getWidth(), jLabelContact_picture.getHeight(), Image.SCALE_SMOOTH);
//        Image pic = ((ImageIcon) jTable1.getValueAt(rowIndex, 6)).getImage().getScaledInstance(jLabel_imageicon.getWidth(), jLabel_imageicon.getHeight(), Image.SCALE_SMOOTH);
//        jLabel_imageicon.;

//        BufferedImage img = null;
//        try {
//            img = ImageIO.read(new File("C:\\Users\\Sir\\Documents\\admintiket\\images\\1.jpg"));
//        } catch (IOException e) {
//            e.printStackTrace();
//        }
//        BufferedImage dimg;
//        dimg = (BufferedImage) img.getScaledInstance(jLabel_imageicon.getWidth(), jLabel_imageicon.getHeight(), Image.SCALE_SMOOTH);
//        ImageIcon imageIcon = new ImageIcon(dimg);
        
//        jLabel_imageicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1.jpg"))); // NOI18N
//        ImageIcon myImg = jLabel_imageicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("C:\\Users\\Sir\\Documents\\admintiket\\images\\1.jpg")));
        
//        ImageIcon myImg = new ImageIcon("C:\\Users\\Sir\\Documents\\admintiket\\images\\1.jpg");
//        Image img = myImg.getImage();
//        BufferedImage bi = new BufferedImage(img.getWidth(null), img.getHeight(null), BufferedImage.TYPE_INT_ARGB);
//        Graphics g = bi.createGraphics();
//        g.drawImage(img, 0, 0, WIDTH, HEIGHT, null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel_Username = new javax.swing.JLabel();
        jLabelUser_pic = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField_fullname = new javax.swing.JTextField();
        jTextField_phone = new javax.swing.JTextField();
        jTextField_email = new javax.swing.JTextField();
        jComboBox_group = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabelContact_picture = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_address = new javax.swing.JTextArea();
        jButton_browse = new javax.swing.JButton();
        jButton_add = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton_edit = new javax.swing.JButton();
        jLabel = new javax.swing.JLabel();
        jTextField_id = new javax.swing.JTextField();
        jButton_delete = new javax.swing.JButton();
        jButton_first = new javax.swing.JButton();
        jButton_previous = new javax.swing.JButton();
        jButton_next = new javax.swing.JButton();
        jButton_last = new javax.swing.JButton();
        jLabel_imageicon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 204, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("My Contacts");

        jLabel_Username.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_Username.setText("Usename");

        jLabelUser_pic.setBackground(new java.awt.Color(255, 255, 51));
        jLabelUser_pic.setOpaque(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabelUser_pic, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLabel_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(313, 313, 313)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
            .addComponent(jLabelUser_pic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Fullname");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Phone");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Email");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Group");

        jTextField_fullname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jComboBox_group.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox_group.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Family", "Friends", "Work" }));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Profile Picture");

        jLabelContact_picture.setBackground(new java.awt.Color(255, 255, 255));
        jLabelContact_picture.setOpaque(true);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Address");

        jTextArea_address.setColumns(20);
        jTextArea_address.setRows(5);
        jScrollPane1.setViewportView(jTextArea_address);

        jButton_browse.setText("browse");
        jButton_browse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_browseActionPerformed(evt);
            }
        });

        jButton_add.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_add.setText("Add");
        jButton_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_addActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jButton_edit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_edit.setText("Edit");
        jButton_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_editActionPerformed(evt);
            }
        });

        jLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel.setText("ID");

        jTextField_id.setEditable(false);
        jTextField_id.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jButton_delete.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_delete.setText("Delete");
        jButton_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_deleteActionPerformed(evt);
            }
        });

        jButton_first.setText("<<");
        jButton_first.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_firstActionPerformed(evt);
            }
        });

        jButton_previous.setText("<");
        jButton_previous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_previousActionPerformed(evt);
            }
        });

        jButton_next.setText(">");
        jButton_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_nextActionPerformed(evt);
            }
        });

        jButton_last.setText(">>");
        jButton_last.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_lastActionPerformed(evt);
            }
        });

        jLabel_imageicon.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_imageicon.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField_fullname)
                                    .addComponent(jTextField_phone)
                                    .addComponent(jTextField_email)
                                    .addComponent(jComboBox_group, 0, 303, Short.MAX_VALUE)
                                    .addComponent(jTextField_id)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton_first)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_previous)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_next)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_last)))
                        .addGap(53, 53, 53)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelContact_picture, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(71, 71, 71)
                                .addComponent(jButton_browse))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel12)
                                    .addGap(18, 18, 18)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButton_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButton_add, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(93, 93, 93)
                        .addComponent(jLabel_imageicon, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1042, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel)
                    .addComponent(jTextField_id, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jButton_browse)
                                    .addComponent(jLabelContact_picture, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(47, 47, 47)
                                        .addComponent(jLabel_imageicon, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton_add)
                                    .addComponent(jButton_edit)
                                    .addComponent(jButton_delete))
                                .addGap(0, 42, Short.MAX_VALUE))
                            .addComponent(jSeparator1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6)
                            .addComponent(jTextField_fullname, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField_phone)
                                .addGap(2, 2, 2))
                            .addComponent(jLabel7))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_email, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jComboBox_group, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_first)
                            .addComponent(jButton_previous)
                            .addComponent(jButton_next)
                            .addComponent(jButton_last))
                        .addGap(30, 30, 30)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void populateJtable() throws SQLException {
        
        ContactQuery cq = new ContactQuery();
        ArrayList<Contact> clist = cq.contactList(currentUserId);
        
        String[] colNames = {"Id", "Fullname", "Group", "Phone", "Email", "Address", "Image"};
        Object[][] rows = new Object[clist.size()][8];
        
        for(int i=0; i<clist.size(); i++) {
            rows[i][0] = clist.get(i).getCid();
            rows[i][1] = clist.get(i).getFullname();
            rows[i][2] = clist.get(i).getGroupc();
            rows[i][3] = clist.get(i).getPhone();
            rows[i][4] = clist.get(i).getEmail();
            rows[i][5] = clist.get(i).getAddress();
            
            ImageIcon pic = new ImageIcon(new ImageIcon(clist.get(i).getPic()).getImage().getScaledInstance(120, 80, Image.SCALE_SMOOTH));
            rows[i][6] = pic;
            
        }
        
        MyModel md = new MyModel(rows, colNames);
        jTable1.setModel(md);
        jTable1.setRowHeight(80);
        jTable1.getColumnModel().getColumn(5).setPreferredWidth(120);
        
    }
    
    private void jButton_browseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_browseActionPerformed
        
        Myfunction mf = new Myfunction();
        imagePth = mf.browseImage(jLabelContact_picture);
        
        
    }//GEN-LAST:event_jButton_browseActionPerformed

    private void jButton_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_addActionPerformed
        
        String fname = jTextField_fullname.getText();
        String phone = jTextField_phone.getText();
        String address = jTextArea_address.getText();
        String email = jTextField_email.getText();
        String groupc = jComboBox_group.getSelectedItem().toString();
        byte[] img = null;
        
        if(imagePth != null) {
            try {
                Path pth = Paths.get(imagePth);
                img = Files.readAllBytes(pth);
                Contact c = new Contact(null, fname, groupc, phone, email, address, img, currentUserId);
                PreparedStatement statement = null;
                ContactQuery cq = new ContactQuery();
                try {
                    cq.insertContact(c);
                    refreshJtable();
                    clearFields();
                } catch (SQLException ex) {
                    Logger.getLogger(MyContact_Form.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (FileNotFoundException ex) {
                Logger.getLogger(MyContact_Form.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(MyContact_Form.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "You must select a profile picture");
        }
        
    }//GEN-LAST:event_jButton_addActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        
        // display selected JTable row data
        // get selected row index
        int rowIndex = jTable1.getSelectedRow();
        jTextField_id.setText(jTable1.getValueAt(rowIndex, 0).toString());
        jTextField_fullname.setText(jTable1.getValueAt(rowIndex, 1).toString());
        jComboBox_group.setSelectedItem(jTable1.getValueAt(rowIndex, 2).toString());
        jTextField_phone.setText(jTable1.getValueAt(rowIndex, 3).toString());
        jTextField_email.setText(jTable1.getValueAt(rowIndex, 4).toString());
        jTextArea_address.setText(jTable1.getValueAt(rowIndex, 5).toString());
        Image pic = ((ImageIcon) jTable1.getValueAt(rowIndex, 6)).getImage().getScaledInstance(jLabelContact_picture.getWidth(), jLabelContact_picture.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon img = new ImageIcon(pic);
        jLabelContact_picture.setIcon(img);
        
    }//GEN-LAST:event_jTable1MouseClicked

    public void refreshJtable() throws SQLException {
        
        jTable1.setModel(new DefaultTableModel());
        populateJtable();
        
    }
    
    public void clearFields() {
        
        jTextField_id.setText("");
        jTextField_fullname.setText("");
        jTextField_phone.setText("");
        jTextArea_address.setText("");
        jTextField_email.setText("");
        jComboBox_group.setSelectedIndex(0);
        jLabelContact_picture.setIcon(null);
        //set imagePth to null to prevent the user to add unwanted duplicated images
        imagePth = null;
        
    }
    
    private void showData(int index) {
        
        // get selected row index
        jTextField_id.setText(jTable1.getValueAt(index, 0).toString());
        jTextField_fullname.setText(jTable1.getValueAt(index, 1).toString());
        jComboBox_group.setSelectedItem(jTable1.getValueAt(index, 2).toString());
        jTextField_phone.setText(jTable1.getValueAt(index, 3).toString());
        jTextField_email.setText(jTable1.getValueAt(index, 4).toString());
        jTextArea_address.setText(jTable1.getValueAt(index, 5).toString());
        Image pic = ((ImageIcon) jTable1.getValueAt(index, 6)).getImage().getScaledInstance(jLabelContact_picture.getWidth(), jLabelContact_picture.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon img = new ImageIcon(pic);
        jLabelContact_picture.setIcon(img);
        
    }
    
    private void jButton_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_editActionPerformed
        
        // the user must select a contact to delete
        if(!jTextField_id.getText().equals("") || imagePth != null) {
            int id = Integer.valueOf(jTextField_id.getText());
            String fname = jTextField_fullname.getText();
            String phone = jTextField_phone.getText();
            String address = jTextArea_address.getText();
            String email = jTextField_email.getText();
            String groupc = jComboBox_group.getSelectedItem().toString();
            byte[] img = null;

            // if the user want to update data and image
            if(imagePth != null) {
                try {
                    Path pth = Paths.get(imagePth);
                    img = Files.readAllBytes(pth);
                    Contact c = new Contact(id, fname, groupc, phone, email, address, img, currentUserId);

                    PreparedStatement statement = null;
                    ContactQuery cq = new ContactQuery();
                    try {
                        cq.updateContact(c, true);
                        refreshJtable();
                        clearFields();
                    } catch (SQLException ex) {
                        Logger.getLogger(MyContact_Form.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(MyContact_Form.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(MyContact_Form.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                Contact c = new Contact(id, fname, groupc, phone, email, address, null, currentUserId);
                PreparedStatement statement = null;
                ContactQuery cq = new ContactQuery();
                try {
                    cq.updateContact(c, false);
                    refreshJtable();
                    clearFields();
                } catch (SQLException ex) {
                    Logger.getLogger(MyContact_Form.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Select a contact from a table");
        }
        
    }//GEN-LAST:event_jButton_editActionPerformed

    private void jButton_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_deleteActionPerformed
        
        // the user must select a contact to delete
        if(!jTextField_id.getText().equals("")) {
            int id = Integer.valueOf(jTextField_id.getText());
            ContactQuery cq = new ContactQuery();
            try {
                cq.deleteContact(id);
                refreshJtable();
                clearFields();
            } catch (SQLException ex) {
                Logger.getLogger(MyContact_Form.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Select a contact from a table");
        }
        
    }//GEN-LAST:event_jButton_deleteActionPerformed

    private void jButton_firstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_firstActionPerformed
        pos = 0;
        showData(pos);
    }//GEN-LAST:event_jButton_firstActionPerformed

    private void jButton_previousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_previousActionPerformed
        pos--;
        showData(pos);
    }//GEN-LAST:event_jButton_previousActionPerformed

    private void jButton_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_nextActionPerformed
        pos++;
        showData(pos);
    }//GEN-LAST:event_jButton_nextActionPerformed

    private void jButton_lastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_lastActionPerformed
        pos = jTable1.getRowCount() - 1;
        showData(pos);
    }//GEN-LAST:event_jButton_lastActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyContact_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyContact_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyContact_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyContact_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                Login_Form form = new Login_Form();
                form.setVisible(true);
                form.pack();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_add;
    private javax.swing.JButton jButton_browse;
    private javax.swing.JButton jButton_delete;
    private javax.swing.JButton jButton_edit;
    private javax.swing.JButton jButton_first;
    private javax.swing.JButton jButton_last;
    private javax.swing.JButton jButton_next;
    private javax.swing.JButton jButton_previous;
    private javax.swing.JComboBox<String> jComboBox_group;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelContact_picture;
    public javax.swing.JLabel jLabelUser_pic;
    public javax.swing.JLabel jLabel_Username;
    private javax.swing.JLabel jLabel_imageicon;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea_address;
    private javax.swing.JTextField jTextField_email;
    private javax.swing.JTextField jTextField_fullname;
    private javax.swing.JTextField jTextField_id;
    private javax.swing.JTextField jTextField_phone;
    // End of variables declaration//GEN-END:variables
}
